# Generated by Django 5.0.7 on 2024-07-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_student_studentinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
        migrations.AlterModelTable(
            name='speciality',
            table='speciality',
        ),
    ]
