# Generated by Django 5.0.7 on 2024-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='subjects',
            field=models.ManyToManyField(to='course.subject'),
        ),
    ]
